package nl.vu.ai.lsde.enron.parser


// run with:
// scala-2.11 -cp parser/target/scala-2.10/parser.jar nl.vu.ai.lsde.enron.parser.Test
object Test extends App {

    // scalastyle:off line.size.limit
    val tests = Seq(
        "Date: Wed, 7 Feb 2001 14:11:00 -0800 (PST)\nFrom: Harry Arora\nTo: Enron\nSubject: Allan Sommer\nX-SDOC: 528063\nX-ZLID: zl-edrm-enron-v2-arora-h-914.eml\n\nHello, email!\n\n***********\nEDRM Enron Email Data Set has been produced in EML, PST and NSF format by ZL Technologies, Inc. This Data Set is licensed under a Creative Commons Attribution 3.0 United States License <http://creativecommons.org/licenses/by/3.0/us/> . To provide attribution, please cite to \"ZL Technologies, Inc. (http://www.zlti.com).\"\n***********",
        "Date: Tue, 29 Jan 2002 14:45:09 -0800 (PST)\nSubject: Notice to Employees of Bankruptcy Court Order\nFrom: Legal - James Derrick Jr. <mbx_annclegal@ENRON.com>\nTo: DL-GA-all_enron_worldwide3 <DL-GA-all_enron_worldwide3@ENRON.com>\nX-SDOC: 105986\nX-ZLID: zl-edrm-enron-v2-townsend-j-127.eml\n\nThis is to inform you that on January 25, 2002 the Honorable Arthur Gonzalez, United States Bankruptcy Judge for the Southern District of New York, entered an order as follows:\n\nIt is hereby Ordered that until further Order of this Court, Enron Corp., its affiliated debtors-in-possession in these jointly administered chapter 11 proceedings (collectively \"Enron\"), and Enron's employees shall preserve, and refrain from destroying or disposing of, any of Enron's records, either in electronic or paper form.\n\nObviously, any violation of this order will carry serious consequences.  We know that we can depend on you to comply with it fully.\n\nThank you.\n\n***********\nEDRM Enron Email Data Set has been produced in EML, PST and NSF format by ZL Technologies, Inc. This Data Set is licensed under a Creative Commons Attribution 3.0 United States License <http://creativecommons.org/licenses/by/3.0/us/> . To provide attribution, please cite to \"ZL Technologies, Inc. (http://www.zlti.com).\"\n***********",
        "Date: Wed, 30 Jan 2002 22:00:00 -0800 (PST)\nSubject: TE CASHOUT PRICES - January, 2002\nFrom: INFOPOST@DUKE-ENERGY.COM@ENRON <IMCEANOTES-INFOPOST+40DUKE-ENERGY+2ECOM+40ENRON@ENRON.com>\nTo: INFOPOST@DUKE-ENERGY.COM\nX-SDOC: 105971\nX-ZLID: zl-edrm-enron-v2-townsend-j-112.eml\n\nJanuary 31, 2002\n\n           DETERMINATION OF CASHOUT PRICES BY ZONE ($/MMBTU)\n                              January, 2002\n\n.                     5 Week Avg           High         Low\nSTX Zone                $2.288            $2.450      $2.220\nETX Zone                $2.315            $2.520      $2.170\nWLA Zone                $2.310            $2.540      $2.080\nELA Zone                $2.323            $2.550      $2.090\nMARKET AREA             $2.309            $2.515      $2.145\n\n\n\n\n\n*******************************************************************\n\nNOTE:\n\nDuke Energy Gas Transmission respects your online time and privacy.\nYou have received this email because you elected to subscribe. To\nunsubscribe, login to the E-mail Notification Subscription page at\nhttp://www.link.duke-energy.com/script2/Notification.asp\nuncheck the appropriate checkbox, and click the Submit button.\n\n***********\nEDRM Enron Email Data Set has been produced in EML, PST and NSF format by ZL Technologies, Inc. This Data Set is licensed under a Creative Commons Attribution 3.0 United States License <http://creativecommons.org/licenses/by/3.0/us/> . To provide attribution, please cite to \"ZL Technologies, Inc. (http://www.zlti.com).\"\n***********",
        "Date: Mon, 14 May 2001 06:26:00 -0700 (PDT)\nFrom: Outlook Migration Team\nTo: V Charles Weldon, Ed McMichael, Eric Boyt, Eric Moon, Geraldine Irvine, Jin\n\t Guo, Louis Dicarlo, Maria Garza, Mark Breese, Sandy Olitsky, Santiago Garcia,\n\t Steven Curlee, Alexandra Villarreal, Andrea Ring, Brad McKay, Chris Germany,\n\t Scott Hendrickson, Eric Thode, Jennifer Walker, Judy Townsend, Kathie Grabstald,\n\t Kimberly Bates, Mark Koenig, Peter F Keavey, Rebecca Ford, Sandra F Brawner,\n\t Scott Goodell, Scott Neal, Sean Boyle, Susan W Pereira, Victoria Versen, Vladi\n\t Pimenov, Craig Taylor, David Jones, Frank W Vickers, Gil Muhl, John Hodge,\n\t Maureen Smith, Nelson Ferries, Phil DeMoes, Robin Barbe, Ruth Concannon, Tammi\n\t DePaolis, Daniel Lisk, Hillary Mack, Jan Sutherland, Jason Wolfe, Shannon Groenewold,\n\t Shelly Mendel, Stacey J Brewer, Suzanne Christiansen, Ted Evans, Dina Snow,\n\t Kay Young, Lance Schuler-Legal, Vineet Arora, Beth A Ryan, Bill Berkeland,\n\t David A Terlip, Doug Leach, Marc De La Roche, Randal Maffett, Tushar Dhruv,\n\t Yolanda Cordova-Gilbert, Amy Villasenor, Debra Young, Jeff Arnold, John Reese,\n\t Josh Mayes, Larry Fenstad, Mark Adleman, Mary Ann Johnson, Mary Lynne Dix,\n\t Mike Thomas, Morris Brassfield, Rinetia Turner, Robert Geheb, Ruthann Frausto,\n\t Tyrone Brown\nSubject: 3 - URGENT - TO PREVENT LOSS OF INFORMATION\nX-SDOC: 1093157\nX-ZLID: zl-edrm-enron-v2-townsend-j-488.eml\n\nCritical Migration Information:\n\n1. Your scheduled Outlook Migration Date is THE EVENING OF : May 17th\n2. You need to press the \"Save My Data\" button (only once) to send us your \npre-migration information.\n3. You must be connected to the network before you press the button.\n4. If a POP-UP BOX appears, prompting you to \"ABORT, CANCEL OR TRUST SIGNER\" \nplease  select TRUST SIGNER.\n5. Any information you Add to your Personal Address Book, Journal or calendar \nafter you click on the button will need to be manually re-added into Outlook \nafter you have been migrated.\n6. Clicking this button does not complete your migration to Outlook. Your \nmigration will be completed  the evening of your migration date.\n\n\n\n    Failure to click on the button means you WILL NOT get your Calendar, \nContacts, Journal and ToDo information imported into Outlook the day of your \nmigration and could result in up to a 2 week delay to restore this \ninformation.\n\nIf you encounter any errors please contact the resolution center @ \n713-853-1411 \n\n***********\nEDRM Enron Email Data Set has been produced in EML, PST and NSF format by ZL Technologies, Inc. This Data Set is licensed under a Creative Commons Attribution 3.0 United States License <http://creativecommons.org/licenses/by/3.0/us/> . To provide attribution, please cite to \"ZL Technologies, Inc. (http://www.zlti.com).\"\n***********",
        "Date: Mon, 6 Nov 2000 03:25:00 -0800 (PST)\nFrom: Judy Townsend\nTo: Edward D Gottlob, James McKay\nSubject: HPL Meter\nX-SDOC: 1093281\nX-ZLID: zl-edrm-enron-v2-townsend-j-601.eml\n\n---------------------- Forwarded by Judy Townsend/HOU/ECT on 11/06/2000 11:18 \nAM ---------------------------\n\n\nlamoss@duke-energy.com on 11/01/2000 08:44:48 AM\nTo: judy.townsend@enron.com\ncc:  \nSubject: HPL Meter\n\n\n     Alan Lambeth out of our Baytown office is who they can talk to about\nthat meter.\nHist # is 281.424.6812.\n\n\n\n\n\n***********\nEDRM Enron Email Data Set has been produced in EML, PST and NSF format by ZL Technologies, Inc. This Data Set is licensed under a Creative Commons Attribution 3.0 United States License <http://creativecommons.org/licenses/by/3.0/us/> . To provide attribution, please cite to \"ZL Technologies, Inc. (http://www.zlti.com).\"\n***********"
    )
    // scalastyle:on line.size.limit

    tests map EmailParser.parse foreach println
}
